defaults: &defaults
  #working_directory: ./circleci
  docker:
    - image: circleci/node:8

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  eslint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run eslint
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run test-ci
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare
      - eslint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
